### ISSUE TITLE
Install aiida-z2pack will downgrage the versions of aiida and more other packages installed for my case.

### ISSUE THREAD

**Issue by hongyi-zhao** [AntimoMarrazzo/aiida-z2pack#3]
Hi, 

See the problem described [here](https://github.com/aiidateam/aiida-core/issues/3920).

Regards

**Comment by AntimoMarrazzo** [comment]
Hi,

this is due to the requirements in the dependencies of AiiDA-z2pack, indeed I was a bit strict with on the versions of the packages. Could you tell us exactly which specific package has conflicts with aiida-core latest version? Thanks.
In the future I will remove some of the strict requirements.
HTH.

**Comment by hongyi-zhao** [comment]
To be frankly, I cannot give you the exact info for this problem now due to that it was reported some time ago. When I have time, I will reinstall aiida-core and this plugin for inspecting the current status.

Regards,
HY

**Comment by Crivella** [comment]
Fixed by #6
